### ISSUE TITLE
Motor Mount issues and request for Keyback

### ISSUE THREAD

**Issue by ArtemisStiles** [forgiven/Ender-3-S1-COREXZ#1]
Excellent mod, I would like to start with. My S1 has never been more consistent and it's running faster than even. Unfortunately, I've noticed a fairly major flaw with how it's designed currently.

The Motor Mounts deform over the length of a print when made from PETG, especially on the Z axis (right) side.

Now there are a couple of solutions that come to mind, those being use ABS and/or reduce the stepper voltage via the potentiometer on the main board, but my assumption is that the goal is accessibility with this mod, so I thought one should be made aware.

Another flaw I have noticed (and I know you probably have too) is the lack of a Z axis retention system in the case of a power loss or when the steppers turn off at idle. The Switchwire uses a Keyback retractable key ring to solve this issue, but that can't work with the current design and would likely involve redesigning a mount or two. Still, this is a fairly important feature in preventing wear and damage to the Toolhead and bed, so if you are still looking to improve the design I highly request this become an added feature.

**Comment by forgiven** [comment]
Hey thanks for the feedback! To answer your suggestions:
**"The Motor Mounts deform over the length of a print when made from PETG, especially on the Z axis (right) side."**
  - I have not had any issues with motor mounts deforming with PETG, be sure to use 4 external perimeters and around 50% grid infill. Maybe your stepper motors are running too hot? Mine will get quite warm over long periods of time, but no warping with the PETG stepper motor mounts.

**"Another flaw I have noticed (and I know you probably have too) is the lack of a Z axis retention system"**
 - This is correct, I have attached one on my printer, it does not work very well, but it does help, I will look at making a more suitable mount for it.

My time for this project is limited unfortunately, so updates could take a while.

**Comment by ArtemisStiles** [comment]
Following up, thank you for replying! 

**"Maybe your stepper motors are running too hot?"**

- It turns out that due to the dual Z system that Creality used, VREF for Z was set to 1.5v (yikes!). I tuned it down to 1.2v in line with the X and Y VREFs and we shall see if that helps. I already replaced the mounts with ABS, so I highly doubt those will melt, but at the very least the Z stepper should remain cooler.

**"...I will look at making a more suitable mount for it."**

- Awesome, that will make a better experience overall with this system. One thought would be to include it as part of the right motor mount (more room), run it up to a pulley on the top mount (through the old Z screw hole perhaps?), then run it down to a mount on the back of the V roller bracket. With one of the heavier Keybacks (like the 14oz, though I think I saw a 30oz one too?) it should perform rather well, as it would be similar to the Voron SW Keyback system.

**"My time for this project is limited unfortunately, so updates could take a while."**

- No worries! I am just trying to contribute how I can. I love what you have done with this so far, and despite the growing pains, I patiently look forward to what else you can think of!
