### ISSUE TITLE
X carriage step files and number of teeth on the XZ steppers

### ISSUE THREAD

**Issue by BGurUpei** [forgiven/Ender-3-S1-COREXZ#2]
the title says it, I was wondering how you made 2 gt2 belts fit per side on the x carriage also you included the klipper config, but in the BOM the gt2 adapters for the steppers are not listed, so I'm wondering what you used, since on the gantry the tolerances are fairly tight and I want to make sure I have proper tolerances for the belt

**Comment by forgiven** [comment]
Hello, I have updated to BOM to include the motors, you can use any nema 17 motors that come with most ender 3 printers. Though you need to align the pulleys with the gantry belt pulleys. You need to know the spec of your stepper motors to configure them accordingly.

The gantry pulleys are comprised of the F695 2RS Bearings (5x13x4) and Stainless steel Flat Washer (5x10x1) and kept in place with an M5 bolt. I have updated the onshape assembly to give some idea. Hope this helps.

![image](https://user-images.githubusercontent.com/137270/231683922-3aff1c24-b164-474e-85ad-67ea62a420ff.png)
