### ISSUE TITLE
Modification if being used in V2 instead

### ISSUE THREAD

**Issue by dhupee** [forgiven/Ender-3-S1-COREXZ#3]
Hey, great mod you got there

so I'm planning to klipperize and corexz my Ender 3 V2, found this mod and I like it, but I have few questions

1. regarding the difference in S1 and V2 what do you think parts that might need be created differently or at least modified
2. Why PLA+ and not ABS like Voron has, isnt PLA+ gonna soft and creeping for this sort of usage

**Comment by forgiven** [comment]
Hi there

Thanks!

To answer your questions:
    1. This mod is quite particular to the Ender 3 S1. I never owned an Ender 3 V2 so I cannot say what work would be required.
    2. ABS can also work fine, I did not have a printer that could print ABS, but should be more suitable.

I've made the `.step` file available if anyone would like to adapt it to their needs.

**Comment by dhupee** [comment]
That's more than enough, I appreciate that you answer

Typical Ender 3 like V2 that I own should be able to print ABS, but with draft or mouse ears to maximize the results, but I need to research more

But really the fact that you share the step file is more than enough

Thanks a lot, starred
