### ISSUE TITLE
No project license listed

### ISSUE THREAD

**Issue by jamincollins** [forgiven/Ender-3-S1-COREXZ#5]
The printables link for the parts shows:
https://creativecommons.org/licenses/by-nc-sa/4.0/

I'm asking for license clarifications as I would like to potentially add some improvements to this project, but need to clarify the license terms as some of the additions might be derivatives of GPLv3 based works.  And GPLv3 and CC BY-NC-SA 4.0 are not compatible with one another:

> Currently, no non-CC licenses have been designated as compatible with BY-NC-SA 4.0. Other licenses may be added to this list at any time according to the established [process and criteria](http://wiki.creativecommons.org/ShareAlike_compatibility_process_and_criteria). Once a license has been added to this list, it will not be removed.

However, if the **NC** part of the license terms is dropped then it is compatible with the GPLv3:

> GPLv3: The [GNU General Public License version 3 ](https://www.gnu.org/copyleft/gpl.html)was declared a “BY-SA–Compatible License” for version 4.0 on 8 October 2015. Note that compatibility with the GPLv3 is one-way only, which means you may license your contributions to adaptations of BY-SA 4.0 materials under GPLv3, but you may not license your contributions to adaptations of GPLv3 projects under BY-SA 4.0. Other [special considerations](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3) apply. See the full [analysis](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3) and [comparison](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility_analysis:_GPL) for more information.

Reference: 
https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses

**Comment by forgiven** [comment]
Hi.

The license is the one defined on Printables.
